apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: 192.168.6.149
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.12
clusterName: cluster_01
networking:
  podSubnet: "172.31.0.0/16"
  serviceSubnet: "172.32.0.0/16"
controlPlaneEndpoint: "192.168.6.159:6443"
imageRepository: registry.aliyuncs.com/google_containers
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
maxPods: 64
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
